import React, { Component } from 'react'
import { Page, Text, View, Document, StyleSheet, Image, } from '@react-pdf/renderer';
import { PDFViewer } from '@react-pdf/renderer';
import axios from 'axios';

// PrintProfile class to generate a CV 
class PrintPEng extends Component {
    // initial state 
    constructor(props) {
        super(props);
        this.state = {
            name: "", // nom d'expert
            lastname: "", // prénom d'expert
            phone: "", // numéro portable d'expert
            email:"", // email expert
            visa:"", // visa expert
            carteSud:"", // carte sud 
            aptMedicale:'', // aptitude médicale
            education:'', // parcours universitaire
            expYear:'', // années d'expériences
            experience:"", // à propos expérince
            expertiseArr:[], // tableau expertise
            certfiArr:[], // tableau certification
            isModified: false, // variable pour l'animation du button 
            presentation:""//presentation d'expert
        };
    }
    // get data from data base 
    componentDidMount () {
        axios.get("/expertsList/" + this.props.id ).then(res => this.setState({
          ...res.data  // obtenir toutes variables de la base de donnés et les envoyer au constructor 
        }
          ))}

    render() {
        return (
            <div style={styles.container}>
                <PDFViewer width="100%" height="900px">
                    <Document>
                        <Page size="A4" style={styles.page} >
                            <View style={styles.body}>
                                <Image
                                    style={styles.image}
                                    src={require('../../Media/logo-falcon.png')}
                                />
                                 <View>
                                    <Text style={styles.title}>{this.state.name.toLocaleUpperCase()}{' '}{this.state.lastname.toLocaleUpperCase()}</Text>
                                </View>
                                <View style={styles.hr}/>
                                
                               
                              
                                <View >
                                    <Text style={styles.info}>Phone: {this.state.phone} </Text>
                                </View>
                                <View >
                                    <Text style={styles.info}>Email: {this.state.email} </Text>
                                </View>
                                <View style={styles.hr}/>
                                <View >
                                    <Text style={styles.descriptions}>Profile</Text>
                                    <Text style={styles.descriptionsText}>{this.state.presentation}</Text>
                                </View>
                                <View style={styles.hr}/>

                                <View >
                                    <Text style={styles.descriptions}>Education</Text>
                                    <Text style={styles.descriptionsText}>{this.state.education}</Text>
                                </View>
                                <View style={styles.hr}/>
                                <View wrap={false}>
                                    <Text style={styles.descriptions}>Experience</Text>
                                    <Text style={styles.descriptionsText}>{this.state.experience}</Text>
                                </View>
                                <View style={styles.hr}/>
                                <View >
                                    <Text style={styles.descriptions}>Qualifications</Text>
                                    {this.state.expertiseArr.filter(item => item.checked).map((el, i) => {
                                       return <Text style={styles.options} key={i}>{el.value}</Text>
                                        })
                                    }
                                </View>
                                                                <View style={styles.hr}/>

                                <View >
                                <Text style={styles.descriptions}>Certifications</Text>
                                    {this.state.certfiArr.filter(item => item.checked).map((el, i) => {
                                       return <Text style={styles.options} key={i}>{el.value}</Text>
                                        })
                                    }
                                </View>
                            </View>
                            <Text style={styles.textFooter}>Generated by Falcon</Text>
                        </Page>
                    </Document>
                </PDFViewer>
            </div>
        )
    }
}
export default PrintPEng;


// style the component

const styles = StyleSheet.create({
    page:{
        paddingTop: 30,
        paddingBottom: 35,
        paddingHorizontal: 25,
        
       
    },
    body: {
        borderTopColor:'black',
        borderWidth:2,
        borderStyle:'solid',
        height:'100%',
        
      },
    title: { 
      margin: 10,
      
      padding: 10,
      textAlign:'center',
      fontSize:20,
      fontWeight:'bold',
        color: '#15317E'
    },
    info: {
            marginLeft:10,
            marginBottom:10,
            fontSize:12,
            
    },
    descriptions:{
        textAlign: 'center',
        margin:10,
        fontWeight: 'bold',
        color: '#15317E'
    },
     descriptionsText:{
       
       

        margin: 12,
        fontSize: 14,
        textAlign: 'justify',
        flexWrap:'wrap'
        
       

    },
    options:{
        marginRight:20,
        marginLeft:20,
                fontSize:15,

    },
    container: {
        textAlign:'center',
        marginTop: 65,
    },
    image: {
        marginVertical: 25,
        marginHorizontal: 10,
        width:150,
        height:55,
    },
    hr:{
        borderBottomColor: 'black',
        borderBottomWidth: 1,
        marginHorizontal:10,
        margin: 10,
      
      padding: 10,
    },
    textFooter:{
        textAlign:'right',
        fontSize:8,
        marginTop:5,
    },
  });